importScripts(['service-worker.js']);

let sw = new ServiceWorkerJS();

sw.precache('precached', [
	'./',
	'./complex.min.js',
	'./favicon.ico',
	'./main.js',
	'./translation.js',
	'./manifest.json',
	'./mic.js',
	'./main.css',
	'./images/all-released_de.svg',
	'./images/all-released_en.svg',
	'./images/all-released_it.svg',
	'./images/all-released_ja.svg',
	'./images/all-released_ko-KR.svg',
	'./images/all-released_zh-CN.svg',
	'./images/all-released_zh-TW.svg',
	'./images/back.svg',
	'./images/coin5yen.png',
	'./images/gear.svg',
	'./images/hypnosis-released_de.svg',
	'./images/hypnosis-released_en.svg',
	'./images/hypnosis-released_it.svg',
	'./images/hypnosis-released_ja.svg',
	'./images/hypnosis-released_ko-KR.svg',
	'./images/hypnosis-released_zh-CN.svg',
	'./images/hypnosis-released_zh-TW.svg',
	'./images/killing-hypnosis_de.svg',
	'./images/killing-hypnosis_en.svg',
	'./images/killing-hypnosis_it.svg',
	'./images/killing-hypnosis_ja.svg',
	'./images/killing-hypnosis_ko-KR.svg',
	'./images/killing-hypnosis_zh-CN.svg',
	'./images/killing-hypnosis_zh-TW.svg',
	'./images/logo_de.svg',
	'./images/logo_en.svg',
	'./images/logo_it.svg',
	'./images/logo_ja.svg',
	'./images/logo_ko-KR.svg',
	'./images/logo_zh-CN.svg',
	'./images/logo_zh-TW.svg',
	'./images/mic.svg',
	'./images/play.svg',
	'./images/please-tap-here_de.svg',
	'./images/please-tap-here_en.svg',
	'./images/please-tap-here_it.svg',
	'./images/please-tap-here_ja.svg',
	'./images/please-tap-here_ko-KR.svg',
	'./images/please-tap-here_zh-CN.svg',
	'./images/please-tap-here_zh-TW.svg',
	'./images/question.svg',
	'./images/sound.svg',
	'./images/stop.svg',
	'./images/speak.svg',
	'./images/spiral.svg',
]);

sw.addRoute(/.*\.mp3$/, { method: 'get' }, sw.networkOnly({ timeout: 3000 }));
